### ISSUE TITLE
[BUG/ member] member session 선언범위 오류

### ISSUE THREAD

**Issue by seoyeonDev** [seoyeonDev/Su-p#131]
## 어떤 버그인가요?
> 버그에 대해 간결하게 설명해주세요.
<img width="806" alt="image" src="https://github.com/seoyeonDev/Su-p/assets/117549232/0534c5ad-b0ec-4a70-b70f-0e3be54fbb1e">

범위 안에 session 추가만 하면 되는 에러. 수정했는지 여부를 알 수 없어 로그인세션 담당자 할당

## 어떤 상황에서 발생한 버그인가요?
> 버그 발생을 확인하기 위한 단계를 작성해주세요.

## 예상 결과
> 예상한 정상적인 결과에 대해 명확하게 설명해주세요.

**Comment by Ohnus** [comment]
원래 if 단에 선언해놨었는데 얼마 전에 머지 꼬였을 때 같이 꼬인 듯 합니다.
if단으로 복구해놨습니다. #125 pr 참고바랍니다.

**Comment by seoyeonDev** [comment]
확인했습니다
