### ISSUE TITLE
[BUG/ studygroup] 테이블 컬럼명 오류

### ISSUE THREAD

**Issue by seoyeonDev** [seoyeonDev/Su-p#148]
## 어떤 버그인가요?
> 버그에 대해 간결하게 설명해주세요.
* studygroup desc 테이블 컬럼명 오류 수정

## 어떤 상황에서 발생한 버그인가요?
> 버그 발생을 확인하기 위한 단계를 작성해주세요.
* **테이블 컬럼명을 ERD 에 맞게 수정해주십시오.**

## 예상 결과
> 예상한 정상적인 결과에 대해 명확하게 설명해주세요.

## 참고할만한 자료 (선택)
<img width="443" alt="image" src="https://github.com/seoyeonDev/Su-p/assets/117549232/d1bcd7f2-402c-45c5-a3ee-2a3d5c2993b5">

**Comment by haeburney** [comment]
desc가 db 예약어로 되어있어서 study_desc로 수정하였습니다. 이에 맞춰 erd를 수정하겠습니다.

**Comment by seoyeonDev** [comment]
> desc가 db 예약어로 되어있어서 study_desc로 수정하였습니다. 이에 맞춰 erd를 수정하겠습니다.

네 그렇게 해주세요 👍
