### ISSUE TITLE
[BUG/ member] login 메서드명 중복

### ISSUE THREAD

**Issue by seoyeonDev** [seoyeonDev/Su-p#89]
## 어떤 버그인가요?
> 버그에 대해 간결하게 설명해주세요.
메서드명 중복 
* 기능상 문제는 없지만 명확한 메서드명을 사용해 혼란 방지 요청

## 어떤 상황에서 발생한 버그인가요?
> 버그 발생을 확인하기 위한 단계를 작성해주세요.
1. String login
2. void login  
두개 메서드의 용도 및 기능 명확화 필요

## 예상 결과
> 예상한 정상적인 결과에 대해 명확하게 설명해주세요.

**Comment by Ohnus** [comment]
void login 메서드 아이디 중복검사 메서드로 활용
