### ISSUE TITLE
[BUG/ group] group DDL 업로드 필요

### ISSUE THREAD

**Issue by seoyeonDev** [seoyeonDev/Su-p#90]
## 어떤 버그인가요?
> 버그에 대해 간결하게 설명해주세요.
* group DDL 누락
* group -> studygroup 그룹명 변경 
* 코드 내용도 변경

## 어떤 상황에서 발생한 버그인가요?
> 버그 발생을 확인하기 위한 단계를 작성해주세요.

## 예상 결과
> 예상한 정상적인 결과에 대해 명확하게 설명해주세요.

**Comment by Ohnus** [comment]
ddl 문서 업데이트 완료
코드 업데이트 완료
